export const BUS_EVENTS = {
    //PLATFORM
    CREATE_PLATFORM: 'CREATE_PLATFORM',
    READ_PLATFORM: 'READ_PLATFORM',
    UPDATE_PLATFORM: 'UPDATE_PLATFORM',
    DELETE_PLATFORM: 'DELETE_PLATFORM',
    //UI
    UPDATE_NAVBAR: 'UPDATE_NAVBAR',
}